### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by Nottt** [HessiJames/mkv-bash-tools#2]
I'm working to do somewhat what you did here, but adding a few more stuff. I could use someone better than me with bash.

Would you like to join forces?

**Comment by dfaust** [comment]
Well, I wouldn't consider this project "active". After all it's just a collection of some small scripts I needed at some point. I just wanted to share them, so others wouldn't have to re-invent the wheel. So I'm not really interested in extending them much further. If you have small improvements, I would be happy about a pull request, though. Otherwise I hope you can learn something from them.
What "more stuff" are you working on?

**Comment by Nottt** [comment]
I understand and I'm doing exactly what you are doing. You can lookup my scripts repo, I'm starting to build the documentation now. 

I just need help with some features I would like to know, let me know if you would be interested in helping with a little of code.

Main issue I want to fix now is having my remove audio script to be able to guess audio quality, as to avoid duplicated audio tracks of same language. Currently it will allow duplicate audio tracks :(

**Comment by dfaust** [comment]
I had a look at your script, but I think you want to achieve something very different than me. I don't want my script to do any guessing, it should do just one simple thing. As I said, it was never meant to be more than that.
So I'm sorry, that I can't help you. But I wish you the best for your project.
